### ISSUE TITLE
Batteries with no content shown in the overview and webserver

### ISSUE THREAD

**Issue by ai-republic** [ai-republic/bms-to-inverter#17]
When using Pylon HV BMS with non-incremental identifiers for batteries there are batteries shown
with no content in the overview and webserver.

**Comment by ai-republic** [comment]
I changed the incremental battery list to a battery mapping which dynamically will add the batteries depending on their identifier.

@jenshermans could you test this that there are no more batteries listed with SOC -1 and 0 (zero) values in the log?

**Comment by jenshermans** [comment]
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14402436/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Did you update? Because it's still showing 2 battery packs.On 26/2/24, 17:29 Jens Hermans ***@***.***> wrote:

   
  BMS-to-Inverter.log

**Comment by jenshermans** [comment]
I'm pretty sure i did it, downloaded again and this is the current log.
Still showing multiple BMS's.
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14403641/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Ok, thank you Jens. I will have to check that again in more detail.

**Comment by ai-republic** [comment]
@jenshermans please update again. There was a merge conflict so some code was not committed. I think that's why we're seeing the first invalid BMS. Now it should be fine. I also tested it emulating the Pylon HV BMS with receiving 0x42x1 messages and its looks fine.

**Comment by jenshermans** [comment]
Only showing one BMS now.

Noticed a little bug in the configurator, the "BMS-ID" keeps showing 0, even if configured something else.

Here i configured my id to 2;
![image](https://github.com/ai-republic/bms-to-inverter/assets/60035424/90c2cdbc-70b9-4fd6-868d-efc875d3b6a2)
When pressing edit, it shows ID: 0, in the edit screen.

[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14414365/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hi Jens, 
super. And I also fixed the _Configurator_ bug you found.
