### ISSUE TITLE
Raspberry Pi 5 compatibility

### ISSUE THREAD

**Issue by DezR** [ai-republic/bms-to-inverter#27]
Not really important to fix since Pi 4's are still easily obtainable.
It might be worthwhile putting a warning that the Pi 5 and Waveshare RS485/CAN adapter may (probably) not work and still a work in progress.

Just in case anyone (like me :) ) think to get a Pi 5 because it's the newest.

**Comment by ai-republic** [comment]
Yes. still didn't get a working solution for the Waveshare RS485/CAN hat from Waveshare support.

**Comment by ai-republic** [comment]
Closing this issue now since it is really a manufacturer problem
