### ISSUE TITLE
Support for deye battery 

### ISSUE THREAD

**Issue by sarzyk** [ai-republic/bms-to-inverter#36]
Hi is any chance to make possibility communication between JK BMS (PB version) and Deye RW-M6.1 battery via RS485 or can?

Thank for reply.

**Comment by ai-republic** [comment]
Hi, 
I'm not sure what you want to do. The Deye RW-M6.1 is a battery system with its own BMS. What exactly do you want with the do with the JK BMS? Do you want to connect 2 batteries (the Deye and another via JK)? 

If so, yes, it is possible to use different BMSes with this application. You will need a separate CAN port for different BMS types. So you could for example run 5 JK BMSes on one CAN port and the Deye on another.

**Comment by sarzyk** [comment]
Hi. Thank for reply.
I wish that :
In deye set charge and discharge maximum for 80A and for the JK for 140A.

**Comment by ai-republic** [comment]
I think you can set the max charge/discharges settings with the software that comes for your JK and Deye BMS

**Comment by ai-republic** [comment]
Closing this issue since I have not heard anything for a long time. Please create a new issue if you encounter any problems.
