### ISSUE TITLE
Support for Growatt MOD series(RS485)

### ISSUE THREAD

**Issue by Star442** [ai-republic/bms-to-inverter#39]
Hi,

Is there any plan of supporting growatt MOD series? It's RS485 based

**Comment by ai-republic** [comment]
Hi,If you could provide the RS485 communication specification then I can surely support it :} On 11/7/24, 21:09 Selver ***@***.***> wrote:

   
  Hi, 
  Is there any plan of supporting growatt MOD series? It's RS485 based

**Comment by ai-republic** [comment]
Great thanks for the inverter protocol specification! Which BMS will you be using? 
I will try to start implementing it next weekend as I'm quite busy at the moment.

**Comment by ai-republic** [comment]
Ok, I would recommend using the Pylontech protocol as its a very widespread commonly used protocol by many BMSes and inverters.
If you like to support this project I'd be very happy! Just click on the **_Sponsor_** link on the [project page](https://github.com/sponsors/ai-republic)! :)

**Comment by ai-republic** [comment]
I will try to finish it this weekend :)

**Comment by ai-republic** [comment]
Hi,
I got around to start the implementation but I was very busy last week (also my sons birthday and an upgrade of my solar system). I think I can finish it this weekend though :)

**Comment by ai-republic** [comment]
@Star442  the Pylon RS485 binding is now implemented. Please get the new _Configurator_ , choose _PYLON_RS485_ in the inverter tab and do a _Clean install_.
Please also configure the debug log-level so that I can check if there are any prolems.
Happy testing ;)

**Comment by ai-republic** [comment]
No, there is only a dummy inverter, but no dummy battery. But that's a good idea - I will implement that in the next few days :)

**Comment by ai-republic** [comment]
I've created a plugin architecture and a plugin that has some preset (dummy) battery data but currently only for 48V systems that is currently only configured for the SMA. I'd like to create an extra tab on the _Configurator_  app where available plugins can be configured. Need to see when I get around to implementing that. Hopefully next weekend 😃

**Comment by ai-republic** [comment]
@Star442 I did add the dummy (_NONE_) BMS now. Also I added plugin support. So if you like to used the dummy BMS you can do so by configuring that on the BMS tab of the latest _Configurator_ application. Then also choose the inverter plugin _SimulatedBatteryPackPlugin_. Please be careful when using this, as it will not report any errors to the inverter and the inverter will try to start charging/discharging without any battery attached !!!! So you **_MUST (!!!!!!!!!!)_**  **disconnect** any **load** and **PV DC input** to prevent possible damage!!!

**Comment by ai-republic** [comment]
@Star442 were you able to test the dummy (_NONE_) battery with the _SimulatedBatteryPackPlugin_ inverter plugin?

**Comment by romanbetwo** [comment]
I am curretnly testing on growatt MOD 10ktl.
Since I am on windows machine, I am not sure if its okay,
So I see 2 BMS's both showing 0 values, I did preconfig the fake battery values, all my DC on inverter is off :)  but on "Server" side of growatt I dont see any info about the battery.

**Comment by ai-republic** [comment]
Windows should be fine if you don't use CAN.
And then you choose _PYLON_RS485_ inverter binding and the _SimulatedBatteryPackPlugin_?

**Comment by romanbetwo** [comment]
Hi ,yep settings were correct, but inverter did not show any data about the battery.

Today I am going to try with  SPH10000.

I will run it on Pi 
Connect all together and I will post full info with simulated batt pack.

**Comment by ai-republic** [comment]
@Star442 I implemented the _GROWATT_MODBUS_ inverter binding now. Could you give it a try and attach the log file here please?

**Comment by romanbetwo** [comment]
Hi, so SPH10000 has CAN battery. Ill finish my coffee and send you log.

**Comment by romanbetwo** [comment]
Okay, 
![IMG_20241006_094037](https://github.com/user-attachments/assets/9df9a59c-95aa-4df0-83cb-a0d215336ec3)
I am unable to run remote desktop for some reason here is screenshot 😑

**Comment by ai-republic** [comment]
Hmm, I'll have to look into that as it really doesn't send a valid frame

**Comment by romanbetwo** [comment]
Torsten, just reminder my current setup is with SPH10000. I am using growatt_can 
Waveshare canusb 
Pi4

**Comment by ai-republic** [comment]
ok, could you please download the latest _Configurator_ application and test this again. The `SimulatedBatteryPackPlugin` should work now. 
FYI: I separated the log files now for BMS-to-Inverter, webserver and MQTT.
Please let me know how it goes and also attach the _bmstoinverter.log_, Thanks 😄

**Comment by ai-republic** [comment]
@romanbetwo did you get a chance to test the fix? Any updates?

**Comment by romanbetwo** [comment]
Hi Torsten, not yet. Next week I will access the MOD. I will update the status for sure.

But the good news is that SPH seems to communicate.

**Comment by romanbetwo** [comment]
![IMG_20241128_150130.jpg](https://github.com/user-attachments/assets/d22d66ae-4cf7-4045-8b8b-7417bd99cb31)

Okay boys most of HW is ready current setup is on photo
Torsten by any chance your mail ?

Try to mail me bee2twoo at gmail com for communication specs.
You are looking at SPH 10000 and HV 20kW prototype battery

**Comment by ErikssonPer** [comment]
Oh, a fellow Growatt SPH owner, nice.

Almost got my diy hv battery done, missing some small items but I'm charging it in lead/acid mode just to check some stuff.
34 kWh with 100cells as it is now and has an Emus G1 BMS, hoping to be able to use this application to make it work with the inverter.
It looks like a really good app.

Also have another SPH with an ARK 10kWh battery
![IMG20241129202538](https://github.com/user-attachments/assets/5700ea3f-1135-456a-9897-c06cee1f0484)

**Comment by romanbetwo** [comment]
Now thats a setup I like !

**Comment by romanbetwo** [comment]
Okay, first thing's first .. Finaly I get my hands on MOD10k

MOD uses growatt modbus 
I attached the protocol for HV ARK battery (like nobody have it just me and supplier :D ) 

[Growatt_BMS_RS485_protocal_1xSxxP_ESS_V2.01.pdf](https://github.com/user-attachments/files/18157056/Growatt_BMS_RS485_protocal_1xSxxP_ESS_V2.01.pdf)

**Comment by ErikssonPer** [comment]
> Hi Torsten, not yet. Next week I will access the MOD. I will update the status for sure.
> 
> But the good news is that SPH seems to communicate.

Did you try it with a battery and bms also or just in dummy bms mode?

**Comment by romanbetwo** [comment]
Hi just dummy test, but since I saw battery open message i do believe it will work out at last the communication. I will make some tests this week probably.. I have been very busy lately..

**Comment by ErikssonPer** [comment]
Tested and the ARK bms I have have a very different canprotocol than what bms-to-inverter is sending out, I'll create a new thread with my findings.

**Comment by romanbetwo** [comment]
Did you try Pylontech-HV?

**Comment by ErikssonPer** [comment]
Yes, 
New thread for growatt SPH [https://github.com/ai-republic/bms-to-inverter/issues/85](url)
