### ISSUE TITLE
Jk BMS to Solplanet Inverter

### ISSUE THREAD

**Issue by Lino34s** [ai-republic/bms-to-inverter#40]
Hey man! Kudos for this amazing project.
Is there any chance on getting my new Nissan leaf battery pack with jk bms to communicate with my asw3680 hybrid inverter via rs485

I guess the inverter doesn't have Can because I had it linked flawlessly with my pylonteck bank via rs485 and I just can't find any reference on the product manual either

**Comment by ai-republic** [comment]
Hi,
yes, I'm going to start implementing the RS485 PylonTech protocol this weeking, so if you use your JK BMS and your inverter can communicate via the Pylon RS485 protocol then it should be no problem.

**Comment by ai-republic** [comment]
Sorry, didn't get round to it this weekend, but I see what I can do until next :)

**Comment by Lino34s** [comment]
Hey Torsten,

I guess I figured out my Solplanet inverter also supports CAN communication.

Do you think I’ll be able to get them to communicate? Because JK BMS also
emulate pylonteck, for example, and I didn’t get

Thank you very much,
Diogo Lino


Torsten Oltmanns ***@***.***> escreveu em dom., 21/07/2024 às
11:42 :

**Comment by ai-republic** [comment]
So your JK does CAN and also the inverter right? And both 'speak' the PylonTech communication specification?

**Comment by Lino34s** [comment]
Yes they does, because first, until a couple months ago,  I had my
Solplanet inverter fully integrated with a 5kwh pylonteck bank (by rs485).
I just did a 18kwh powerwall with jk BMS from my old Nissan leaf

Com os melhores cumprimentos,
Diogo Lino


Torsten Oltmanns ***@***.***> escreveu em dom., 21/07/2024 às
12:53 :

**Comment by ai-republic** [comment]
In that case, yes my application can communicate with both your BMS(es) and inverter :)

**Comment by Lino34s** [comment]
I would like to take this opportunity to include the document with the communication protocol for my Solplanet ASW3680H-S2 Inverter

[ASW3000~6000H-S2 communication_protocol (CN).pdf](https://github.com/user-attachments/files/16418457/ASW3000.6000H-S2.communication_protocol.CN.pdf)

**Comment by ai-republic** [comment]
Thanks for the communication specification. As your Solplanet inverter supports the PylonTech RS485 protocol I would recommend to use this. I'm still implementing the binding but hope to finish it this weekend

**Comment by Lino34s** [comment]
Perfect!

I'm also waiting for the rs485 Can Hat for RaspPi to come in the next few days. I guess I might need some little help on the assembly 

Thanks a lot man

**Comment by ai-republic** [comment]
@Lino34s  the Pylon RS485 binding is now implemented. Please get the new _Configurator_ , choose _PYLON_RS485_ in the inverter tab and do a _Clean install_.
Please also configure the debug log-level so that I can check if there are any prolems.
Happy testing ;)

**Comment by Lino34s** [comment]
Can you please provide me with an image of the CAN Hat/Inverter setup, including the respective cabling and connections?

**Comment by ai-republic** [comment]
Hi @Lino34s, 
this is different for each BMS, CAN hat and inverter depending on your model. But in the manuals you should find the corresponding plugs and PIN layout for the connections. Then you just need to connect CAN H to CAN H and CAN L to CAN L with the correct pins. 
In general like this:
![image](https://github.com/user-attachments/assets/0d1125c3-5fb0-409a-a953-30e850986564)

**Comment by Lino34s** [comment]
Sorry. Is that the 1CH or 2CH CAN HAT? I just bought the 1xCH one since I thought of using CAN on the BMS side and rs485 on the inverter side. Am I correct?
I am currently preparing the cable connections. If I understand correctly, the BMS connection is made on the pins, and the inverter connection is made on that green SP3485 interface chip from de right. Only those 4x cables from your scheme are used right?

**Comment by ai-republic** [comment]
It would be a 1CH CAN/RS485 hat similar to this https://www.waveshare.com/rs485-can-hat.htm

**Comment by Lino34s** [comment]
Getting these logs when trying to read BMS data
![image](https://github.com/user-attachments/assets/24b79504-649b-43ee-aad6-1885d4ce7158)

**Comment by ai-republic** [comment]
Hmm, looks like you specified a CAN port for a RS_485 binding. Could you attach your config.properties file here please?

**Comment by Lino34s** [comment]
[config.txt](https://github.com/user-attachments/files/16841342/config.txt)

**Comment by ai-republic** [comment]
Ah, you have the JK on `can0` and also the BMS which is a Pylon RS485. The Pylon should be on a port like `/dev/ttyXXX`

**Comment by ai-republic** [comment]
I guess I can close this as there has been no news for over a month. Please feel free to reopen this issue if you need further assistance.
