### ISSUE TITLE
Support for SAJ B2/BU2

### ISSUE THREAD

**Issue by stonedswede** [ai-republic/bms-to-inverter#49]
Hello, 

it would be awesome if you could try to integrate the SAJ HS2/B2/BU2 battery storage solution. 

they are capable of both Modbus RTU as TCP and u know by experience that they have hidden functions all over their body.

**Comment by ai-republic** [comment]
Hi, if you can provdide the protocol communication specification I'm sure I can integrate it.

**Comment by ai-republic** [comment]
I guess this can be closed as its been stale for over a month now. Please feel free to open another issue if you need more assistance
