### ISSUE TITLE
Growatt low voltage (CAN) BMS

### ISSUE THREAD

**Issue by TyngRikku** [ai-republic/bms-to-inverter#50]
In the application, I can not find this option for the BMS, is it named differently?

Thanks

**Comment by ai-republic** [comment]
Could you please tell me what BMS or Growatt battery system you have?

**Comment by TyngRikku** [comment]
Its a growatt sph5000 and greenbatt batteries (I have two single phase PV systems, one with growatt and one huawei)

thanks

**Comment by ai-republic** [comment]
So the inverter is a Growatt SPH5000 and the batteries are Greenbatt. The inverter is supported by the application. Do you have any information on the Greenbatt battery? Which CAN communication specification does it use? As its chinese I suspect it will support the Pylon specification. Can you log in to the Greenbatt BMS or get a CAN dump?

**Comment by TyngRikku** [comment]
Hey Torsten

I can select multiple CAN protocols, of which the Pylontech CAN looks the logical choice. The BMS is from Shanghai Enjie. I have no idea how to do a CAN dump :-)

**Comment by ai-republic** [comment]
@TyngRikku I'd need some kind of specification for the BMS to move on

**Comment by ai-republic** [comment]
@TyngRikku I will close this as there has been no correspondance for over a month. If you need assistance please feel free to reopen this or create another issue
