### ISSUE TITLE
Support for EG4 6000XP Inverter

### ISSUE THREAD

**Issue by danielbeardsley** [ai-republic/bms-to-inverter#56]
The [EG4 6000XP](https://signaturesolar.com/eg4-6000xp-off-grid-inverter-split-phase/) has become really popular and I'm interested in connect a DIY battery to it.

The have a ["battery compatibility list"](https://eg4electronics.com/wp-content/uploads/2024/04/EG4-6000XP-Battery-Compatibility-List.pdf) but it's not clear that they have an explicit protocol that the inverter speaks.

**Comment by ai-republic** [comment]
You can definetely use the _PYLON_RS485_ binding for the inverter as it only supports RS485. That should work with the existing application :)

**Comment by ai-republic** [comment]
I guess this can be closed. Please open another ticket if you need further assistance. If everything works find I'd be very thankful for any [donation](https://github.com/sponsors/ai-republic) 😄
