### ISSUE TITLE
Huawei inverter connects to third-party battery BMS

### ISSUE THREAD

**Issue by 930680849** [ai-republic/bms-to-inverter#72]
Spend Huawei Inverter Connected to DIY Battery BMS?
![1729087372293](https://github.com/user-attachments/assets/d2882b3a-ff7e-4a9c-b1a5-bb799e2b2bc2)
![Uploading 微信图片_20241016220314.png…]()

**Comment by ai-republic** [comment]
Yes, that is supported. What is you're issue?

**Comment by 930680849** [comment]
华为需要DCDC高压电池

**Comment by ai-republic** [comment]
Yes, the Huawei Inverter uses HV. So either you have a HV battery or you can put batteries in series to match the required voltage, e.g. put 10x48V in series to achieve 480V.

**Comment by 930680849** [comment]
> 是的，华为逆变器使用HV。因此，您要么有高压电池，要么您可以将电池串联以匹配所需的电压，例如将10x48V串联以达到480V。

我这里有DCDC模块 380-48双向

**Comment by 930680849** [comment]
> 是的，华为逆变器使用HV。因此，您要么有高压电池，要么您可以将电池串联以匹配所需的电压，例如将10x48V串联以达到480V。

能否增加pace bms？

**Comment by ai-republic** [comment]
I believe you will need a BMS that supports your voltage needs (i.e. 450V or 600V or similar). You cannot put i.e. 48V BMSes in series as the voltage will increase for each battery pack.

**Comment by 930680849** [comment]
> 我相信您需要一个支持您电压需求的 BMS（即 450V 或 600V 或类似电压）。您不能将 48V BMS 串联起来，因为每个电池组的电压都会增加。

需要你的协议支持 
![image](https://github.com/user-attachments/assets/05d042e5-dc8c-4fb5-a9ad-b4504d703613)

**Comment by 930680849** [comment]
能否增加pace485bms？

**Comment by ai-republic** [comment]
What's the image above? It that your Pace BMS? What do you mean with 'increased'? You mean to tweak a Pace BMS from 48V to 480V? I don't know anything about that and I don't think its possible.

**Comment by 930680849** [comment]
pace 480-48 48-480需要注入华为协议

**Comment by ai-republic** [comment]
I'm sorry but I can't make any sense of the translations. You'll need to go into more detail and be more specific what you intend to do and how.

**Comment by 930680849** [comment]
留下个邮箱

**Comment by ai-republic** [comment]
If you need assistance with the application, please post it here. I cannot give you tips on how to tweak your BMS hardware from 48V to 480V.

**Comment by ai-republic** [comment]
Closing this issue as it has been inactive for over 2 weeks
