### ISSUE TITLE
Docs update, Tian Power 48100-LT-06 and Growatt 3000ES

### ISSUE THREAD

**Issue by aren** [ai-republic/bms-to-inverter#76]
Note that GROWATT_CAN did not work for me on my 3000ES, so I'm using PYLON_CAN instead.

[tianpower.patch](https://github.com/user-attachments/files/17578613/tianpower.patch)

**Comment by ai-republic** [comment]
@aren thanks, will integrate that into the wiki 👍

**Comment by ai-republic** [comment]
Added it to the Wiki 😄
